#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/dat/xl_test_data
  
  bl_listgen \
    -d ../xl_test_data \
    -1L  \
    -u $DVCZ_UDIR \
    -X .ssh \
    $@
  
else
  echo "DEV_BASE is not defined"
fi
