#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/dat/xl_testData
  
  bl_listgen \
    -d ../xl_testData \
    -1L  \
    -u $DVCZ_UDIR \
    -X .ssh \
    $@
  
else
  echo "DEV_BASE is not defined"
fi
